fixtures:
  repositories:
    stdlib:
      repo: https://github.com/puppetlabs/puppetlabs-stdlib.git
      ref: 4.11.0
    mysql:
      repo: https://github.com/puppetlabs/puppetlabs-mysql.git
      ref: 3.10.0
    java:
      repo: https://github.com/puppetlabs/puppetlabs-java.git
      ref: 1.6.0
    java_ks:
      repo: https://github.com/puppetlabs/puppetlabs-java_ks.git
      ref: 1.4.1
    archive:
      repo: https://github.com/voxpupuli/puppet-archive.git
      ref: v1.3.0
    systemd:
      repo: https://github.com/camptocamp/puppet-systemd.git
      ref: 0.4.0
  symlinks:
    keycloak: "#{source_dir}"
